### ISSUE TITLE
pyqtgraph crashes when 'copy' export images

### ISSUE THREAD

**Issue by HuangJunye** [HuangJunye/GrapheneLab-Measurement-Code#37]
The pyqtgraph crashes when I tried to copy the export images

**Comment by HuangJunye** [comment]
Request timed out: ('getObjAttr', 29879, 0, b'\x80\x03}q\x00(X\x03\x00\x00\x00objq\x01cpyqtgraph.multiprocess.remoteproxy\nunpickleObjectProxy\nq\x02(M\xc0\rMl\x10X\x02\x00\x00\x00[]q\x03)tq\x04Rq\x05X\x04\x00\x00\x00attrq\x06X\x06\x00\x00\x00extendq\x07X\n\x00\x00\x00returnTypeq\x08X\x04\x00\x00\x00autoq\tu.')
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 486, in start
    self.io_loop.start()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 127, in start
    self.asyncio_loop.run_forever()
  File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 422, in run_forever
    self._run_once()
  File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 1432, in _run_once
    handle._run()
  File "C:\ProgramData\Anaconda3\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 117, in _handle_events
    handler_func(fileobj, events)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 450, in _handle_events
    self._handle_recv()
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 480, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2662, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2785, in _run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2909, in run_ast_nodes
    if self.run_code(code, result):
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-8-80b6023af8b9>", line 8, in <module>
    ignore_magnet=True
  File "C:\Users\adminnus\Documents\Github\GrapheneLab-Measurement-Code\measurement\do_fridge_sweep.py", line 195, in do_fridge_sweep
    plot_data.extend(to_plot, _callSync='off')
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyqtgraph\multiprocess\remoteproxy.py", line 897, in __getattr__
    return self._handler.getObjAttr(self, attr, **opts)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyqtgraph\multiprocess\remoteproxy.py", line 532, in getObjAttr
    return self.send(request='getObjAttr', opts=dict(obj=obj, attr=attr), **kwds)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyqtgraph\multiprocess\remoteproxy.py", line 470, in send
    return req.result()
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyqtgraph\multiprocess\remoteproxy.py", line 643, in result
    traceback.print_stack()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-8-80b6023af8b9> in <module>()
      6     timeout=0,
      7     comment=comment_string,
----> 8     ignore_magnet=True
      9 )

~\Documents\Github\GrapheneLab-Measurement-Code\measurement\do_fridge_sweep.py in do_fridge_sweep(graph_proc, rpg, data_file, read_inst, set_inst, set_value, pre_value, finish_value, fridge_sweep, fridge_set, sweep_start, sweep_stop, sweep_rate, sweep_finish, persist, delay, sample, timeout, wait, max_over_time, return_data, socket_data_number, comment, network_dir, ignore_magnet)
    193 
    194         # Pass data to the plots
--> 195         plot_data.extend(to_plot, _callSync='off')
    196         for j in range(num_of_inst):
    197             curve[j].setData(x=plot_data[0::(num_of_inst + 1)], y=plot_data[j + 1::(num_of_inst + 1)], _callSync='off')

TypeError: 'Request' object is not callable
